[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[lib]
name = "hello_world"
crate-type = ["cdylib"]

[dependencies]
japanese-address-parser = "0.1.0-alpha.6"
jni = "0.21.1"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["rt"] }
